#!/bin/bash

set -e

OREGON_NORTH_SRS='EPSG:2913'
SHP_SIMPLIFICATION=0.0001

usage() {
  echo "Usage: $0 [-d database name] [-o out file or /dev/stdout] [-a TSP area N, NE, NW, CENTRAL, FAR_SE, etc.]" 1>&2; exit 1;
}

while getopts ":d:o:a:" opt; do
  case ${opt} in
    d) db_name=$OPTARG;;
    o) out_file=$OPTARG;;
    a) area=$OPTARG;;
    *) usage;;
  esac
done

if [[ -z $db_name || -z $out_file || -z $area ]]; then usage; fi

area=`echo ${area} | tr '[:upper:]' '[:lower:]'`

tmp_dir=`mktemp -t housing -d`

ogr2ogr -f "GeoJSON" $tmp_dir/rivers.geojson \
  -t_srs $OREGON_NORTH_SRS \
  -s_srs 'EPSG:4326' \
  -simplify $SHP_SIMPLIFICATION \
  PG:"dbname=${db_name}" \
  -sql "select st_union(st_intersection(tsp.geom, rivers.geom)) as geom \
    from tsp_districts tsp  \
    inner join rivers on st_intersects(tsp.geom, rivers.geom) \
    where lower(districtna) = '${area}' and st_isvalid(rivers.geom)"

ogr2ogr -f "GeoJSON" $tmp_dir/blockgroups.geojson \
  -t_srs $OREGON_NORTH_SRS \
  -s_srs 'EPSG:4326' \
  -simplify $SHP_SIMPLIFICATION \
  PG:"dbname=${db_name}" \
  -sql "select st_intersection(tsp.geom, acs.wkb_geometry) as geom, acs.*, lai.* \
    from tsp_districts tsp \
    inner join acs_2013_5yr_bg_41_oregon acs on st_intersects(tsp.geom, acs.wkb_geometry) \
    inner join lai on lai.blkgrp = acs.geoid
    where lower(districtna) = '${area}' and st_isvalid(acs.wkb_geometry)"

ogr2ogr -f "GeoJSON" $tmp_dir/streets.geojson \
  -t_srs $OREGON_NORTH_SRS \
  -s_srs 'EPSG:4326' \
  -simplify $SHP_SIMPLIFICATION \
  PG:"dbname=${db_name}" \
  -sql "select st_union(st_intersection(tsp.geom, streets.geom)) as geom \
    from tsp_districts tsp  \
    inner join streets on st_intersects(tsp.geom, streets.geom) \
    where lower(districtna) = '${area}' and st_isvalid(streets.geom)"

ogr2ogr -f "GeoJSON" $tmp_dir/parks.geojson \
  -t_srs $OREGON_NORTH_SRS \
  -s_srs 'EPSG:4326' \
  -simplify $SHP_SIMPLIFICATION \
  PG:"dbname=${db_name}" \
  -sql "select st_union(st_intersection(tsp.geom, parks.geom)) as geom \
    from tsp_districts tsp  \
    inner join parks on st_intersects(tsp.geom, parks.geom) \
    where lower(districtna) = '${area}' and st_isvalid(parks.geom)"

ogr2ogr -f "GeoJSON" $tmp_dir/buildings.geojson \
  -t_srs $OREGON_NORTH_SRS \
  -s_srs 'EPSG:4326' \
  -simplify $SHP_SIMPLIFICATION \
  PG:"dbname=${db_name}" \
  -sql "select st_union(st_intersection(tsp.geom, buildings.geom)) as geom \
    from tsp_districts tsp  \
    inner join buildings on st_intersects(tsp.geom, buildings.geom) \
    where lower(districtna) = '${area}' and st_isvalid(buildings.geom)"

topojson \
  -o $out_file \
  -s .25 \
  -p bmio=+blkgrp_median_income_owners \
  -p bmir=+blkgrp_median_income_renters \
  --cartesian \
  --width 800 \
  --height 800 \
  -- $tmp_dir/rivers.geojson \
     $tmp_dir/blockgroups.geojson \
     $tmp_dir/streets.geojson \
     $tmp_dir/parks.geojson \
     $tmp_dir/buildings.geojson

rm -rf $tmp_dir
